/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ArticleDao;
import dao.ClientDao;
import dao.CommandeDao;
import dao.FournisseurDao;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Article;
import model.Client;
import model.Fournisseur;

/**
 *
 * @author bynan_gamer
 */
public class Appli extends javax.swing.JFrame {
    public static int index = 0;
    public static int iText;
    public static int quantiteAvantUpdate;
    /**
     * Creates new form Appli
     */
    public Appli() throws SQLException {
        initComponents();
        initStockTable();
        initComboList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeStockTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomFournisseurTextField = new javax.swing.JTextField();
        nomArticleTextField = new javax.swing.JTextField();
        quantiteTextField = new javax.swing.JTextField();
        fournisseurComboBox = new javax.swing.JComboBox();
        ajoutFournisseurButton = new javax.swing.JButton();
        ajoutArticleButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clientNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        quantiteCommandeTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        informationCommandeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Stock");

        listeStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listeStockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeStockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeStockTable);

        jLabel2.setText("Ajouter nouvel article:");

        jLabel3.setText("Nom: ");

        jLabel4.setText("Quantité:");

        jLabel5.setText("Fournisseur:");

        jLabel6.setText("Ajouter un fournisseur:");

        nomFournisseurTextField.setToolTipText("Nom du fournisseur");

        nomArticleTextField.setToolTipText("Nom de l'article");

        quantiteTextField.setToolTipText("Quantité");

        fournisseurComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fournisseurComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fournisseurComboBoxActionPerformed(evt);
            }
        });

        ajoutFournisseurButton.setText(" Ajouter Fournisseur");
        ajoutFournisseurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutFournisseurButtonActionPerformed(evt);
            }
        });

        ajoutArticleButton.setText("Ajouter Article");
        ajoutArticleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutArticleButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Liste des articles dans le stock");

        jLabel8.setText("Effectuer une commande:");

        jLabel9.setText("Client");

        jLabel10.setText("Quantité");

        jButton1.setText("Confirmer la commande");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        informationCommandeLabel.setText("Cliquez sur le tableau pour sélectionner un produit à commander.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fournisseurComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ajoutArticleButton)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomArticleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(quantiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomFournisseurTextField))
                                .addComponent(ajoutFournisseurButton)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(informationCommandeLabel)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(quantiteCommandeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel8))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nomFournisseurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajoutFournisseurButton)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nomArticleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quantiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(fournisseurComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(ajoutArticleButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(informationCommandeLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantiteCommandeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutFournisseurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutFournisseurButtonActionPerformed
        // TODO add your handling code here:
        String nom = nomFournisseurTextField.getText();
        
        Fournisseur fournisseurModel = new Fournisseur();
        fournisseurModel.setNom(nom);
        FournisseurDao fournisseurDao = new FournisseurDao();
        fournisseurDao.addFournisseur(fournisseurModel);
        nomFournisseurTextField.setText("");
        JOptionPane.showMessageDialog(null, "Succès!");
        fournisseurComboBoxModel.removeAllElements();
        try {
            initComboList();
        } catch (SQLException ex) {
            Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ajoutFournisseurButtonActionPerformed

    private void fournisseurComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fournisseurComboBoxActionPerformed
        
    }//GEN-LAST:event_fournisseurComboBoxActionPerformed

    private void ajoutArticleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutArticleButtonActionPerformed
        
        String nomArticle = nomArticleTextField.getText();
        String quantite = quantiteTextField.getText();
        Fournisseur fournisseurModel = (Fournisseur) fournisseurComboBox.getSelectedItem();
        
        Article article = new Article();
        article.setNom(nomArticle);
        article.setQuantite(Integer.parseInt(quantite));
        
        ArticleDao articleDao = new ArticleDao();
        try {
            articleDao.addArticle(article, fournisseurModel.getId());
        } catch (SQLException ex) {
            Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Succès!");
        nomArticleTextField.setText("");
        quantiteTextField.setText("");
        try {
            initStockTable();
        } catch (SQLException ex) {
            Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ajoutArticleButtonActionPerformed

    private void listeStockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeStockTableMouseClicked
        index = listeStockTable.getSelectedRow();
        try {
            showArticleSelected(index);
        } catch (SQLException ex) {
            Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listeStockTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            addCommande();
        } catch (SQLException ex) {
            Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Appli().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutArticleButton;
    private javax.swing.JButton ajoutFournisseurButton;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JComboBox fournisseurComboBox;
    private javax.swing.JLabel informationCommandeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listeStockTable;
    private javax.swing.JTextField nomArticleTextField;
    private javax.swing.JTextField nomFournisseurTextField;
    private javax.swing.JTextField quantiteCommandeTextField;
    private javax.swing.JTextField quantiteTextField;
    // End of variables declaration//GEN-END:variables
    private final DefaultComboBoxModel fournisseurComboBoxModel = new DefaultComboBoxModel();
    
    
    public void showArticleSelected(int index) throws SQLException {

        if (listeStockTable.getRowCount() != 0) {

            ArticleDao articleDao = new ArticleDao();
            List<Article> articleModel = null;

            articleModel = articleDao.selectAllArticle();

            int i = articleModel.get(index).getId();
            iText = i;

            String nom = articleModel.get(index).getNom();
            int quantite = articleModel.get(index).getQuantite();
            quantiteAvantUpdate = quantite;

            informationCommandeLabel.setText("Nom du produit: "+nom+", quantité disponible: "+ quantite);

        } else {
            System.out.println("Tableau des liste de patients vide");
        }

    }
    
    
    public void initComboList() throws SQLException{
         // init fournisseur
        FournisseurDao fournisseurDao = new FournisseurDao();
        List<Fournisseur> listeFournisseur = fournisseurDao.selectAllFournisseurs();
        for (Object fournisseur : listeFournisseur) {
            Fournisseur f = (Fournisseur) fournisseur;
            fournisseurComboBoxModel.addElement(fournisseur);
        }
        this.fournisseurComboBox.setModel(fournisseurComboBoxModel);
    }
    
    private void initStockTable() throws SQLException {
        String[] columnNames = {"#", "Nom de l'article", "Quantite", "Nom du fournisseur"};

        DefaultTableModel tbMdl = new DefaultTableModel(columnNames, 0);

        tbMdl.setColumnCount(4);

        ArticleDao articleDao = new ArticleDao();

        List<Article> listArticle = new ArrayList();
        listArticle = articleDao.selectAllArticle();
        FournisseurDao fourniDao = new FournisseurDao();

        for (Article a : listArticle) {
            Article article = (Article) a;
            Fournisseur fournisseur = fourniDao.selectById(a.getId_fournisseur());
            tbMdl.addRow(new Object[]{
                a.getId(),
                a.getNom(),
                a.getQuantite(),
                fournisseur.getNom()
            });
        }
        listeStockTable.setModel(tbMdl);

    }

    private void addCommande() throws SQLException {
        String clientName = clientNameTextField.getText();
        String quantiteCommande = quantiteCommandeTextField.getText();
        ClientDao clientDao = new ClientDao();
        Client clientModel = new Client();
        clientModel.setNom(clientName);
        try {
            clientDao.addClient(clientModel);
        } catch (SQLException ex) {
            Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
        }
        CommandeDao commande = new CommandeDao();
        int qteCommande = Integer.parseInt(quantiteCommande);
        commande.addCommande(clientDao.lastId(), iText, qteCommande);
        int quantiteReste = quantiteAvantUpdate -  qteCommande;
        ArticleDao articleDao = new ArticleDao();
        articleDao.updateById(iText, quantiteReste);
        initStockTable();
    }
}
